version: 0.2

phases:
  install:
    commands:
      - pip install -q PyJWT==1.7.1 boto3 prospector coverage==4.5.4 bandit schema pylint_quotes
  pre_build:
    commands:
      - export LOG_LEVEL=CRITICAL
      - export OUR_COMMIT_SHA=`git rev-parse HEAD`
      - bandit -r -q .
      - prospector
      - coverage run --source='.' -m unittest
      - coverage report -m --fail-under=100 --omit=*/__init__.py,tests/*,setup.py,examples/*
